name: Run Golang Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Run unit tests
      run: make run-unit-tests

    - name: Run integration tests
      run: make run-integration-tests
